### ISSUE TITLE
Switch/Replace elements between containers?

### ISSUE THREAD

**Issue by voidale** [bevacqua/dragula#215] opened 2015-09-26 08:02 UTC
Is it possible some how to change the functionality of moving from one container to the other to a switch or replace with other element form the other container? Here is an image that might explain what I'm hoping for:  
![switch](https://cloud.githubusercontent.com/assets/4450730/10116437/aeb613e8-6435-11e5-8a89-15e2d1c051ba.PNG)

Thanks

**Comment by bevacqua** [comment] 2015-09-26 17:41
No idea what you mean, but sounds like a duplicate of #188

**Comment by voidale** [comment] 2015-09-26 17:47
@bevacqua I want 2 items to switch places and not just move them from one container, for example container 1 item 2 replace with container 2 item 1.  And it will be nice to get the numbers with what it has been changed. It's actually fine if it's one container as well doesn't make a difference.

**Comment by bevacqua** [comment] 2015-10-05 17:48
Closing as dupe

**Closed by bevacqua** 2015-10-05 17:48 UTC
