### ISSUE TITLE
Drag and drop multiple items attach them all by control key on keyboard

### ISSUE THREAD

**Issue by Or92** [bevacqua/dragula#523] opened 2017-09-12 19:41 UTC
> Please only use GitHub issues for bug reports and feature requests.
>
> - [ ] Read the [contributing guidelines][contrib]
> - [ ] Bug reports containing repro steps are likely to be fixed faster
> - [ ] Feature requests should be multi-purpose, describe use cases
> - [ ] For support requests or questions, please refer to [our Slack channel][slack]

[contrib]: https://github.com/bevacqua/dragula/blob/master/.github/contributing.markdown
[slack]: https://dragula-slackin.herokuapp.com/

**Comment by benshewmake** [comment] 2018-02-06 12:41
+1 to this feature request. This is a duplicate of #50 but it does not provide any further explanation on how to do implement DnD multiple items. If it's possible to accomplish this with the current version, can someone post an example doing so?

I would argue to expand this feature to cover the CMD key on Mac and even the Shift key (all common multi-selector keys).

**Closed** 2020-09-29 11:55 UTC
