### ISSUE TITLE
Item missplaced on drag

### ISSUE THREAD

**Issue by pindamonhangaba** [bevacqua/dragula#8] opened 2015-04-15 18:35 UTC
Something I noticed when trying out the samples on Firefox 39.0a2: http://imgur.com/8YPS2OP
When you drag the second example, the dragged items stay near the previous example. On the screen cap you can't see the mouse cursor, but it is down on the second box.

Tested on IE 11.0.96 and happens the same.

**Comment by bevacqua** [comment] 2015-04-15 18:41
Closing as duplicate of #5

**Closed by bevacqua** 2015-04-15 18:41 UTC
