### ISSUE TITLE
Use CSS 2d/3d "transform" rather than "left" and "top"

### ISSUE THREAD

**Issue by demrks** [bevacqua/dragula#220] opened 2015-09-30 19:37 UTC
I had a look at the "mirror" element and saw that dragula currently uses the CSS `left` and `right` properties to "attach" it to the mouse cursor.

It'll probably be much more performant to use `transform: translate3d(x,y,0)` or `transform: translate(x,y)` and fall back to `left` and `right` (for older browsers, e.g. IE7/8).

**Comment by bevacqua** [comment] 2015-09-30 20:06
Sure. Closing as a dupe of #210 . Feel free to PR

**Closed by bevacqua** 2015-09-30 20:06 UTC

**Comment by demrks** [comment] 2015-09-30 20:47
Sorry for the duplicate. I would do a pull request, but it seems that there is already a pending pull request in #210, that didn't get accepted or declined (https://github.com/romainbessugesmeusy/dragula/commit/2c24df3d9fa712f55b7328de6a3669bfe62a3534)
